### ISSUE TITLE
Run Bridges and Articulation analysis for each pathway.

### ISSUE THREAD

**Issue by LuisFranciscoHS** [PathwayAnalysisPlatform/ProteoformNetworks#10]
- [x] Plot a pathway with the 3 types of construction methods
- [x] Test 3 pathways were constructed correctly
- [x] Get list of all pathways
- [x] Get number and list of articulation points and bridges
- [x] Violin plot for the numbers of each pathway
- [x] Plot a pathway highlighting the articulation points and bridges
- [x] Modify the violin plots to Normalize by size the number of articulation points and bridges with respect to the total number of vertices and edges in the graph
- [x] Select 3 pathways where the numbers change and plot them
- [x] Modify pathway plots to show controls of bokeh to zoom in

**Comment by darkmx** [comment]
:D
